packages:
  - apps/*
  - libs/*
  - samples/*
  - dbs/*
  - plugins/*

autoInstallPeers: true

onlyBuiltDependencies:
  - '@nestjs/core'
  - '@prisma/client'
  - '@prisma/engines'
  - '@scarf/scarf'
  - '@swc/core'
  - esbuild
  - nx
  - prisma
  - unrs-resolver

strictPeerDependencies: false
