export const data = [
  { name: 'Meter', symbol: 'm' },
  { name: 'Millimeter', symbol: 'mm' },
  { name: 'Centimeter', symbol: 'cm' },
  { name: 'Inch', symbol: 'in' },
  { name: 'Foot', symbol: 'ft' },
  { name: 'Kilogram', symbol: 'kg' },
  { name: 'Gram', symbol: 'g' },
  { name: 'Pound', symbol: 'lb' },
  { name: 'Ounce', symbol: 'oz' },
  { name: 'Liter', symbol: 'L' },
  { name: 'Milliliter', symbol: 'mL' },
  { name: 'Gallon (US Liquid)', symbol: 'gal' },
  { name: 'Cubic Foot', symbol: 'ft³' },
  { name: 'Square Meter', symbol: 'm²' },
  { name: 'Square Foot', symbol: 'ft²' },
  { name: 'Second', symbol: 's' },
  { name: 'Hour', symbol: 'hr' },
  { name: 'Watt', symbol: 'W' },
  { name: 'Kilowatt', symbol: 'kW' },
  { name: 'Volt', symbol: 'V' },
  { name: 'Ampere', symbol: 'A' },
  { name: 'Hertz', symbol: 'Hz' },
  { name: 'Gigahertz', symbol: 'GHz' },
  { name: 'Milliamperes hour', symbol: 'mAh' },
  { name: 'Degree Celsius', symbol: '°C' },
  { name: 'Degree Fahrenheit', symbol: '°F' },
  { name: 'US Dollar', symbol: '$' },
  { name: 'Euro', symbol: '€' },
  { name: 'Each', symbol: 'ea' },
  { name: 'Dozen', symbol: 'dz' },
  { name: 'Case', symbol: 'cs' },
  { name: 'Pounds per Square Inch', symbol: 'psi' },
  { name: 'Gigabyte', symbol: 'GB' },
  { name: 'Terabyte', symbol: 'TB' },
];
