export const __Create__ = 'Create';
export const __Update__ = 'Update';
export const __Query__ = 'Query';
export const __QueryOne__ = 'QueryOne';
export const __OrderBy__ = 'OrderBy';
export const __Select__ = 'Select';
export const __Omit__ = 'Omit';
export const __Include__ = 'Include';
export const __Projection__ = 'Projection';
export const __Distinct__ = 'Distinct';
export const __Where__ = 'Where';
export const __Enum__ = 'Enum';
export const __Filter__ = 'Filter';
export const __ArrayFilter__ = 'ArrayFilter';

export const __CreateOwn__ = 'CreateOwn';
export const __UpdateOwn__ = 'UpdateOwn';
export const __QueryOwn__ = 'QueryOwn';
export const __QueryOneOwn__ = 'QueryOneOwn';
export const __OrderByOwn__ = 'OrderByOwn';
export const __SelectOwn__ = 'SelectOwn';
export const __IncludeOwn__ = 'IncludeOwn';
export const __ProjectionOwn__ = 'ProjectionOwn';
export const __WhereOwn__ = 'WhereOwn';

export const toCreate = (name: string) => `${name}${__Create__}`;
export const toUpdate = (name: string) => `${name}${__Update__}`;
export const toQuery = (name: string) => `${name}${__Query__}`;
export const toQueryOne = (name: string) => `${name}${__QueryOne__}`;
export const toOrderBy = (name: string) => `${name}${__OrderBy__}`;
export const toSelect = (name: string) => `${name}${__Select__}`;
export const toOmit = (name: string) => `${name}${__Omit__}`;
export const toInclude = (name: string) => `${name}${__Include__}`;
export const toProjection = (name: string) => `${name}${__Projection__}`;
export const toDistinct = (name: string) => `${name}${__Distinct__}`;
export const toWhere = (name: string) => `${name}${__Where__}`;
export const toEnum = (name: string) => `${name}${__Enum__}`;

// Own
export const toCreateOwn = (name: string) => `${name}${__CreateOwn__}`;
export const toUpdateOwn = (name: string) => `${name}${__UpdateOwn__}`;
export const toQueryOwn = (name: string) => `${name}${__QueryOwn__}`;
export const toQueryOneOwn = (name: string) => `${name}${__QueryOneOwn__}`;
export const toOrderByOwn = (name: string) => `${name}${__OrderByOwn__}`;
export const toSelectOwn = (name: string) => `${name}${__SelectOwn__}`;
export const toIncludeOwn = (name: string) => `${name}${__IncludeOwn__}`;
export const toProjectionOwn = (name: string) => `${name}${__ProjectionOwn__}`;
export const toWhereOwn = (name: string) => `${name}${__WhereOwn__}`;
export const toFilter = (name: string) => `${name}${__Filter__}`;
export const toArrayFilter = (name: string) => `${name}${__ArrayFilter__}`;
