import type { DMMF } from '@prisma/client/runtime/library';

/**
 * Check the field is generated by the database or has any `generated` indication in documentation
 * @param field
 * @returns
 */
export function isGeneratedField(field: DMMF.Field) {
  if (field.kind === 'unsupported') {
    return true;
  }

  if (field.documentation?.includes('@generated')) {
    return true;
  }

  // Any field with named generator such as autoincrement, uuid etc.
  if (field.default) {
    if ((field.default as DMMF.FieldDefault).name) {
      return true;
    }
  }

  if (field.isUpdatedAt) {
    return true;
  }

  return false;
}
