#!/bin/bash

DIR="./generated/schema.prisma"

if [ -f "$DIR" ]; then

  echo "@puq/app-db prisma client already exists"

else

  echo "Generating @puq/app-db prisma client"

  npx prisma migrate dev --name updated

  npx prisma generate
  
fi
