#!/bin/bash

# Define the directory to check
DIR="./generated/schema.prisma"

if [ -f "$DIR" ]; then

  echo "sample-db prisma client already exists"

else

  echo "Generating sample-db prisma client"

  npx prisma migrate dev --name updated

  npx prisma generate

fi
