#!/bin/bash

DIR="./generated/schema.prisma"

if [ -f "$DIR" ]; then

  echo "inventory-db prisma client already exists"

else

  echo "Generating inventory-db prisma client"

  npx prisma migrate dev --name updated

  npx prisma generate
  
fi
